#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "read_loop.h"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(char const *, uInt32 *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 105), // char const *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 10), // uInt32 *
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(int, char *)
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 105), // char *
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(int, uInt32, uInt32, uInt16 *, int, int *, float *, uInt16 *)
/*  9 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 10 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, _cffi_prim_int(sizeof(uInt32), (
           ((uInt32)-1) | 0 /* check that uInt32 is an integer type */
         ) <= 0)), // uInt32
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 107), // uInt16 *
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 14 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int *
/* 15 */ _CFFI_OP(_CFFI_OP_POINTER, 106), // float *
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32)
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, IMG_SIGNAL_TYPE, uInt32, uInt32, uInt32, uInt32)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 23 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // IMG_SIGNAL_TYPE
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32 *)
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32 *, uInt32 *)
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 35 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 36 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 37 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 38 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32)
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 41 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 42 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32, uInt32 *, void * *)
/* 43 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 44 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 45 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 66), // void * *
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32, void * *, uInt32 *, uInt32, uInt32)
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 50 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 51 */ _CFFI_OP(_CFFI_OP_NOOP, 46),
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 53 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 56 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32, void * *, uInt32, uInt32)
/* 57 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 59 */ _CFFI_OP(_CFFI_OP_NOOP, 46),
/* 60 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 61 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 62 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 63 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32, void *)
/* 64 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 65 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 66 */ _CFFI_OP(_CFFI_OP_POINTER, 108), // void *
/* 67 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 68 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, uInt32, void *, IMG_OVERWRITE_MODE, uInt32 *, uInt32 *)
/* 69 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 70 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 71 */ _CFFI_OP(_CFFI_OP_NOOP, 66),
/* 72 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // IMG_OVERWRITE_MODE
/* 73 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 74 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 75 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 76 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, void * *)
/* 77 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 78 */ _CFFI_OP(_CFFI_OP_NOOP, 46),
/* 79 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 80 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, void * *, uInt32)
/* 81 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 82 */ _CFFI_OP(_CFFI_OP_NOOP, 46),
/* 83 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 84 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 85 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, void * *, uInt32, uInt32, uInt32, uInt32, uInt32)
/* 86 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 87 */ _CFFI_OP(_CFFI_OP_NOOP, 46),
/* 88 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 89 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 90 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 91 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 92 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 93 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 94 */ _CFFI_OP(_CFFI_OP_FUNCTION, 5), // int()(uInt32, void * *, uInt32, uInt32, uInt32, uInt32, uInt32, uInt32)
/* 95 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 96 */ _CFFI_OP(_CFFI_OP_NOOP, 46),
/* 97 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 98 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 99 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 100 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 101 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 102 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 103 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 104 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, _cffi_prim_int(sizeof(Int32), (
           ((Int32)-1) | 0 /* check that Int32 is an integer type */
         ) <= 0)), // Int32
/* 105 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 106 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 107 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, _cffi_prim_int(sizeof(uInt16), (
           ((uInt16)-1) | 0 /* check that uInt16 is an integer type */
         ) <= 0)), // uInt16
/* 108 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_IMG_OVERWRITE_GET_OLDEST(unsigned long long *o)
{
  int n = (IMG_OVERWRITE_GET_OLDEST) <= 0;
  *o = (unsigned long long)((IMG_OVERWRITE_GET_OLDEST) | 0);  /* check that IMG_OVERWRITE_GET_OLDEST is an integer */
  return n;
}

static int _cffi_const_IMG_OVERWRITE_GET_NEXT_ITERATION(unsigned long long *o)
{
  int n = (IMG_OVERWRITE_GET_NEXT_ITERATION) <= 0;
  *o = (unsigned long long)((IMG_OVERWRITE_GET_NEXT_ITERATION) | 0);  /* check that IMG_OVERWRITE_GET_NEXT_ITERATION is an integer */
  return n;
}

static int _cffi_const_IMG_OVERWRITE_FAIL(unsigned long long *o)
{
  int n = (IMG_OVERWRITE_FAIL) <= 0;
  *o = (unsigned long long)((IMG_OVERWRITE_FAIL) | 0);  /* check that IMG_OVERWRITE_FAIL is an integer */
  return n;
}

static int _cffi_const_IMG_OVERWRITE_GET_NEWEST(unsigned long long *o)
{
  int n = (IMG_OVERWRITE_GET_NEWEST) <= 0;
  *o = (unsigned long long)((IMG_OVERWRITE_GET_NEWEST) | 0);  /* check that IMG_OVERWRITE_GET_NEWEST is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_NONE(unsigned long long *o)
{
  int n = (IMG_SIGNAL_NONE) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_NONE) | 0);  /* check that IMG_SIGNAL_NONE is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_EXTERNAL(unsigned long long *o)
{
  int n = (IMG_SIGNAL_EXTERNAL) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_EXTERNAL) | 0);  /* check that IMG_SIGNAL_EXTERNAL is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_RTSI(unsigned long long *o)
{
  int n = (IMG_SIGNAL_RTSI) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_RTSI) | 0);  /* check that IMG_SIGNAL_RTSI is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_ISO_IN(unsigned long long *o)
{
  int n = (IMG_SIGNAL_ISO_IN) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_ISO_IN) | 0);  /* check that IMG_SIGNAL_ISO_IN is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_ISO_OUT(unsigned long long *o)
{
  int n = (IMG_SIGNAL_ISO_OUT) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_ISO_OUT) | 0);  /* check that IMG_SIGNAL_ISO_OUT is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_STATUS(unsigned long long *o)
{
  int n = (IMG_SIGNAL_STATUS) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_STATUS) | 0);  /* check that IMG_SIGNAL_STATUS is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_SCALED_ENCODER(unsigned long long *o)
{
  int n = (IMG_SIGNAL_SCALED_ENCODER) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_SCALED_ENCODER) | 0);  /* check that IMG_SIGNAL_SCALED_ENCODER is an integer */
  return n;
}

static int _cffi_const_IMG_SIGNAL_SOFTWARE_TRIGGER(unsigned long long *o)
{
  int n = (IMG_SIGNAL_SOFTWARE_TRIGGER) <= 0;
  *o = (unsigned long long)((IMG_SIGNAL_SOFTWARE_TRIGGER) | 0);  /* check that IMG_SIGNAL_SOFTWARE_TRIGGER is an integer */
  return n;
}

static int _cffi_d_imgClose(uInt32 x0, uInt32 x1)
{
  return imgClose(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgClose(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "imgClose", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgClose(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_imgClose _cffi_d_imgClose
#endif

static int _cffi_d_imgGetAttribute(uInt32 x0, uInt32 x1, void * x2)
{
  return imgGetAttribute(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgGetAttribute(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  void * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "imgGetAttribute", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(66), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(66), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgGetAttribute(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgGetAttribute _cffi_d_imgGetAttribute
#endif

static int _cffi_d_imgGrab(uInt32 x0, void * * x1, uInt32 x2)
{
  return imgGrab(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgGrab(PyObject *self, PyObject *args)
{
  uInt32 x0;
  void * * x1;
  uInt32 x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "imgGrab", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, uInt32);
  if (x2 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgGrab(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgGrab _cffi_d_imgGrab
#endif

static int _cffi_d_imgGrabArea(uInt32 x0, void * * x1, uInt32 x2, uInt32 x3, uInt32 x4, uInt32 x5, uInt32 x6, uInt32 x7)
{
  return imgGrabArea(x0, x1, x2, x3, x4, x5, x6, x7);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgGrabArea(PyObject *self, PyObject *args)
{
  uInt32 x0;
  void * * x1;
  uInt32 x2;
  uInt32 x3;
  uInt32 x4;
  uInt32 x5;
  uInt32 x6;
  uInt32 x7;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;

  if (!PyArg_UnpackTuple(args, "imgGrabArea", 8, 8, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, uInt32);
  if (x2 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uInt32);
  if (x3 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uInt32);
  if (x4 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x5 = _cffi_to_c_int(arg5, uInt32);
  if (x5 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x6 = _cffi_to_c_int(arg6, uInt32);
  if (x6 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x7 = _cffi_to_c_int(arg7, uInt32);
  if (x7 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgGrabArea(x0, x1, x2, x3, x4, x5, x6, x7); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgGrabArea _cffi_d_imgGrabArea
#endif

static int _cffi_d_imgGrabSetup(uInt32 x0, uInt32 x1)
{
  return imgGrabSetup(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgGrabSetup(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "imgGrabSetup", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgGrabSetup(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_imgGrabSetup _cffi_d_imgGrabSetup
#endif

static int _cffi_d_imgInterfaceOpen(char const * x0, uInt32 * x1)
{
  return imgInterfaceOpen(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgInterfaceOpen(PyObject *self, PyObject *args)
{
  char const * x0;
  uInt32 * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "imgInterfaceOpen", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgInterfaceOpen(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgInterfaceOpen _cffi_d_imgInterfaceOpen
#endif

static int _cffi_d_imgRingSetup(uInt32 x0, uInt32 x1, void * * x2, uInt32 x3, uInt32 x4)
{
  return imgRingSetup(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgRingSetup(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  void * * x2;
  uInt32 x3;
  uInt32 x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "imgRingSetup", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x3 = _cffi_to_c_int(arg3, uInt32);
  if (x3 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uInt32);
  if (x4 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgRingSetup(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgRingSetup _cffi_d_imgRingSetup
#endif

static int _cffi_d_imgSequenceSetup(uInt32 x0, uInt32 x1, void * * x2, uInt32 * x3, uInt32 x4, uInt32 x5)
{
  return imgSequenceSetup(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSequenceSetup(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  void * * x2;
  uInt32 * x3;
  uInt32 x4;
  uInt32 x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "imgSequenceSetup", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x4 = _cffi_to_c_int(arg4, uInt32);
  if (x4 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x5 = _cffi_to_c_int(arg5, uInt32);
  if (x5 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSequenceSetup(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSequenceSetup _cffi_d_imgSequenceSetup
#endif

static int _cffi_d_imgSessionCopyBufferByNumber(uInt32 x0, uInt32 x1, void * x2, IMG_OVERWRITE_MODE x3, uInt32 * x4, uInt32 * x5)
{
  return imgSessionCopyBufferByNumber(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionCopyBufferByNumber(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  void * x2;
  IMG_OVERWRITE_MODE x3;
  uInt32 * x4;
  uInt32 * x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "imgSessionCopyBufferByNumber", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(66), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(66), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x3, _cffi_type(72), arg3) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg5, (char **)&x5);
  if (datasize != 0) {
    x5 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg5, (char **)&x5,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionCopyBufferByNumber(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionCopyBufferByNumber _cffi_d_imgSessionCopyBufferByNumber
#endif

static int _cffi_d_imgSessionExamineBuffer2(uInt32 x0, uInt32 x1, uInt32 * x2, void * * x3)
{
  return imgSessionExamineBuffer2(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionExamineBuffer2(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 x1;
  uInt32 * x2;
  void * * x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "imgSessionExamineBuffer2", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionExamineBuffer2(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionExamineBuffer2 _cffi_d_imgSessionExamineBuffer2
#endif

static int _cffi_d_imgSessionOpen(uInt32 x0, uInt32 * x1)
{
  return imgSessionOpen(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionOpen(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "imgSessionOpen", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionOpen(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionOpen _cffi_d_imgSessionOpen
#endif

static int _cffi_d_imgSessionReleaseBuffer(uInt32 x0)
{
  return imgSessionReleaseBuffer(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionReleaseBuffer(PyObject *self, PyObject *arg0)
{
  uInt32 x0;
  int result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionReleaseBuffer(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionReleaseBuffer _cffi_d_imgSessionReleaseBuffer
#endif

static int _cffi_d_imgSessionStartAcquisition(uInt32 x0)
{
  return imgSessionStartAcquisition(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionStartAcquisition(PyObject *self, PyObject *arg0)
{
  uInt32 x0;
  int result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionStartAcquisition(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionStartAcquisition _cffi_d_imgSessionStartAcquisition
#endif

static int _cffi_d_imgSessionStatus(uInt32 x0, uInt32 * x1, uInt32 * x2)
{
  return imgSessionStatus(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionStatus(PyObject *self, PyObject *args)
{
  uInt32 x0;
  uInt32 * x1;
  uInt32 * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "imgSessionStatus", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (uInt32 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionStatus(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionStatus _cffi_d_imgSessionStatus
#endif

static int _cffi_d_imgSessionStopAcquisition(uInt32 x0)
{
  return imgSessionStopAcquisition(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionStopAcquisition(PyObject *self, PyObject *arg0)
{
  uInt32 x0;
  int result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionStopAcquisition(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionStopAcquisition _cffi_d_imgSessionStopAcquisition
#endif

static int _cffi_d_imgSessionTriggerConfigure2(uInt32 x0, IMG_SIGNAL_TYPE x1, uInt32 x2, uInt32 x3, uInt32 x4, uInt32 x5)
{
  return imgSessionTriggerConfigure2(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSessionTriggerConfigure2(PyObject *self, PyObject *args)
{
  uInt32 x0;
  IMG_SIGNAL_TYPE x1;
  uInt32 x2;
  uInt32 x3;
  uInt32 x4;
  uInt32 x5;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "imgSessionTriggerConfigure2", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(23), arg1) < 0)
    return NULL;

  x2 = _cffi_to_c_int(arg2, uInt32);
  if (x2 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uInt32);
  if (x3 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uInt32);
  if (x4 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x5 = _cffi_to_c_int(arg5, uInt32);
  if (x5 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSessionTriggerConfigure2(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_imgSessionTriggerConfigure2 _cffi_d_imgSessionTriggerConfigure2
#endif

static int _cffi_d_imgShowError(int x0, char * x1)
{
  return imgShowError(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgShowError(PyObject *self, PyObject *args)
{
  int x0;
  char * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "imgShowError", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgShowError(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgShowError _cffi_d_imgShowError
#endif

static int _cffi_d_imgSnap(uInt32 x0, void * * x1)
{
  return imgSnap(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSnap(PyObject *self, PyObject *args)
{
  uInt32 x0;
  void * * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "imgSnap", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSnap(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSnap _cffi_d_imgSnap
#endif

static int _cffi_d_imgSnapArea(uInt32 x0, void * * x1, uInt32 x2, uInt32 x3, uInt32 x4, uInt32 x5, uInt32 x6)
{
  return imgSnapArea(x0, x1, x2, x3, x4, x5, x6);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_imgSnapArea(PyObject *self, PyObject *args)
{
  uInt32 x0;
  void * * x1;
  uInt32 x2;
  uInt32 x3;
  uInt32 x4;
  uInt32 x5;
  uInt32 x6;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;

  if (!PyArg_UnpackTuple(args, "imgSnapArea", 7, 7, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uInt32);
  if (x0 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(46), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (void * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(46), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, uInt32);
  if (x2 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uInt32);
  if (x3 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uInt32);
  if (x4 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x5 = _cffi_to_c_int(arg5, uInt32);
  if (x5 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x6 = _cffi_to_c_int(arg6, uInt32);
  if (x6 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = imgSnapArea(x0, x1, x2, x3, x4, x5, x6); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_imgSnapArea _cffi_d_imgSnapArea
#endif

static int _cffi_d_read_n_shots(int x0, uInt32 x1, uInt32 x2, uInt16 * x3, int x4, int * x5, float * x6, uInt16 * x7)
{
  return read_n_shots(x0, x1, x2, x3, x4, x5, x6, x7);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_read_n_shots(PyObject *self, PyObject *args)
{
  int x0;
  uInt32 x1;
  uInt32 x2;
  uInt16 * x3;
  int x4;
  int * x5;
  float * x6;
  uInt16 * x7;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;

  if (!PyArg_UnpackTuple(args, "read_n_shots", 8, 8, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uInt32);
  if (x1 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uInt32);
  if (x2 == (uInt32)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(12), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (uInt16 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(12), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x4 = _cffi_to_c_int(arg4, int);
  if (x4 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(14), arg5, (char **)&x5);
  if (datasize != 0) {
    x5 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(14), arg5, (char **)&x5,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    x6 = ((size_t)datasize) <= 640 ? (float *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(15), arg6, (char **)&x6,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(12), arg7, (char **)&x7);
  if (datasize != 0) {
    x7 = ((size_t)datasize) <= 640 ? (uInt16 *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(12), arg7, (char **)&x7,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = read_n_shots(x0, x1, x2, x3, x4, x5, x6, x7); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_read_n_shots _cffi_d_read_n_shots
#endif

static int _cffi_const_IMG_CURRENT_BUFFER(unsigned long long *o)
{
  int n = (IMG_CURRENT_BUFFER) <= 0;
  *o = (unsigned long long)((IMG_CURRENT_BUFFER) | 0);  /* check that IMG_CURRENT_BUFFER is an integer */
  return n;
}

static int _cffi_const_IMG_EXT_TRIG0(unsigned long long *o)
{
  int n = (IMG_EXT_TRIG0) <= 0;
  *o = (unsigned long long)((IMG_EXT_TRIG0) | 0);  /* check that IMG_EXT_TRIG0 is an integer */
  return n;
}

static int _cffi_const_IMG_LAST_BUFFER(unsigned long long *o)
{
  int n = (IMG_LAST_BUFFER) <= 0;
  *o = (unsigned long long)((IMG_LAST_BUFFER) | 0);  /* check that IMG_LAST_BUFFER is an integer */
  return n;
}

static int _cffi_const_IMG_OLDEST_BUFFER(unsigned long long *o)
{
  int n = (IMG_OLDEST_BUFFER) <= 0;
  *o = (unsigned long long)((IMG_OLDEST_BUFFER) | 0);  /* check that IMG_OLDEST_BUFFER is an integer */
  return n;
}

static int _cffi_const_IMG_TRIG_ACTION_CAPTURE(unsigned long long *o)
{
  int n = (IMG_TRIG_ACTION_CAPTURE) <= 0;
  *o = (unsigned long long)((IMG_TRIG_ACTION_CAPTURE) | 0);  /* check that IMG_TRIG_ACTION_CAPTURE is an integer */
  return n;
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "IMG_CURRENT_BUFFER", (void *)_cffi_const_IMG_CURRENT_BUFFER, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "IMG_EXT_TRIG0", (void *)_cffi_const_IMG_EXT_TRIG0, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "IMG_LAST_BUFFER", (void *)_cffi_const_IMG_LAST_BUFFER, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "IMG_OLDEST_BUFFER", (void *)_cffi_const_IMG_OLDEST_BUFFER, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "IMG_OVERWRITE_FAIL", (void *)_cffi_const_IMG_OVERWRITE_FAIL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_OVERWRITE_GET_NEWEST", (void *)_cffi_const_IMG_OVERWRITE_GET_NEWEST, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_OVERWRITE_GET_NEXT_ITERATION", (void *)_cffi_const_IMG_OVERWRITE_GET_NEXT_ITERATION, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_OVERWRITE_GET_OLDEST", (void *)_cffi_const_IMG_OVERWRITE_GET_OLDEST, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_EXTERNAL", (void *)_cffi_const_IMG_SIGNAL_EXTERNAL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_ISO_IN", (void *)_cffi_const_IMG_SIGNAL_ISO_IN, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_ISO_OUT", (void *)_cffi_const_IMG_SIGNAL_ISO_OUT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_NONE", (void *)_cffi_const_IMG_SIGNAL_NONE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_RTSI", (void *)_cffi_const_IMG_SIGNAL_RTSI, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_SCALED_ENCODER", (void *)_cffi_const_IMG_SIGNAL_SCALED_ENCODER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_SOFTWARE_TRIGGER", (void *)_cffi_const_IMG_SIGNAL_SOFTWARE_TRIGGER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_SIGNAL_STATUS", (void *)_cffi_const_IMG_SIGNAL_STATUS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IMG_TRIG_ACTION_CAPTURE", (void *)_cffi_const_IMG_TRIG_ACTION_CAPTURE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "imgClose", (void *)_cffi_f_imgClose, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 38), (void *)_cffi_d_imgClose },
  { "imgGetAttribute", (void *)_cffi_f_imgGetAttribute, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 63), (void *)_cffi_d_imgGetAttribute },
  { "imgGrab", (void *)_cffi_f_imgGrab, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 80), (void *)_cffi_d_imgGrab },
  { "imgGrabArea", (void *)_cffi_f_imgGrabArea, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 94), (void *)_cffi_d_imgGrabArea },
  { "imgGrabSetup", (void *)_cffi_f_imgGrabSetup, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 38), (void *)_cffi_d_imgGrabSetup },
  { "imgInterfaceOpen", (void *)_cffi_f_imgInterfaceOpen, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_imgInterfaceOpen },
  { "imgRingSetup", (void *)_cffi_f_imgRingSetup, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 56), (void *)_cffi_d_imgRingSetup },
  { "imgSequenceSetup", (void *)_cffi_f_imgSequenceSetup, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 48), (void *)_cffi_d_imgSequenceSetup },
  { "imgSessionCopyBufferByNumber", (void *)_cffi_f_imgSessionCopyBufferByNumber, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 68), (void *)_cffi_d_imgSessionCopyBufferByNumber },
  { "imgSessionExamineBuffer2", (void *)_cffi_f_imgSessionExamineBuffer2, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 42), (void *)_cffi_d_imgSessionExamineBuffer2 },
  { "imgSessionOpen", (void *)_cffi_f_imgSessionOpen, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_imgSessionOpen },
  { "imgSessionReleaseBuffer", (void *)_cffi_f_imgSessionReleaseBuffer, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 18), (void *)_cffi_d_imgSessionReleaseBuffer },
  { "imgSessionStartAcquisition", (void *)_cffi_f_imgSessionStartAcquisition, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 18), (void *)_cffi_d_imgSessionStartAcquisition },
  { "imgSessionStatus", (void *)_cffi_f_imgSessionStatus, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_imgSessionStatus },
  { "imgSessionStopAcquisition", (void *)_cffi_f_imgSessionStopAcquisition, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 18), (void *)_cffi_d_imgSessionStopAcquisition },
  { "imgSessionTriggerConfigure2", (void *)_cffi_f_imgSessionTriggerConfigure2, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d_imgSessionTriggerConfigure2 },
  { "imgShowError", (void *)_cffi_f_imgShowError, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 4), (void *)_cffi_d_imgShowError },
  { "imgSnap", (void *)_cffi_f_imgSnap, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 76), (void *)_cffi_d_imgSnap },
  { "imgSnapArea", (void *)_cffi_f_imgSnapArea, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 85), (void *)_cffi_d_imgSnapArea },
  { "read_n_shots", (void *)_cffi_f_read_n_shots, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 8), (void *)_cffi_d_read_n_shots },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$IMG_OVERWRITE_MODE", 72, _cffi_prim_int(sizeof(IMG_OVERWRITE_MODE), ((IMG_OVERWRITE_MODE)-1) <= 0),
    "IMG_OVERWRITE_GET_OLDEST,IMG_OVERWRITE_GET_NEXT_ITERATION,IMG_OVERWRITE_FAIL,IMG_OVERWRITE_GET_NEWEST" },
  { "$IMG_SIGNAL_TYPE", 23, _cffi_prim_int(sizeof(IMG_SIGNAL_TYPE), ((IMG_SIGNAL_TYPE)-1) <= 0),
    "IMG_SIGNAL_NONE,IMG_SIGNAL_EXTERNAL,IMG_SIGNAL_RTSI,IMG_SIGNAL_ISO_IN,IMG_SIGNAL_ISO_OUT,IMG_SIGNAL_STATUS,IMG_SIGNAL_SCALED_ENCODER,IMG_SIGNAL_SOFTWARE_TRIGGER" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "BUFLIST_ID", 10 },
  { "EVENT_ID", 10 },
  { "GUIHNDL", 10 },
  { "IMG_ERR", 104 },
  { "IMG_OVERWRITE_MODE", 72 },
  { "IMG_SIGNAL_TYPE", 23 },
  { "INTERFACE_ID", 10 },
  { "Int32", 104 },
  { "Int8", 105 },
  { "PULSE_ID", 10 },
  { "SESSION_ID", 10 },
  { "USER_FUNC", 5 },
  { "uInt16", 107 },
  { "uInt32", 10 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  _cffi_enums,
  _cffi_typenames,
  37,  /* num_globals */
  0,  /* num_struct_unions */
  2,  /* num_enums */
  14,  /* num_typenames */
  NULL,  /* no includes */
  109,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__imaqffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__imaqffi(void) { return NULL; }
#  else
     init_imaqffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__imaqffi(void)
{
  return _cffi_init("_imaqffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_imaqffi(void)
{
  _cffi_init("_imaqffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
